# Dump File
#
# Database is ported from MS Access
#--------------------------------------------------------
# Program Version 5.1.232

DROP DATABASE IF EXISTS `art`;
CREATE DATABASE IF NOT EXISTS `art`;
USE `art`;

#
# Table structure for table 'Artists'
#

DROP TABLE IF EXISTS `Artists`;

CREATE TABLE `Artists` (
  `ArtistID` INTEGER NOT NULL AUTO_INCREMENT, 
  `FirstName` VARCHAR(50), 
  `LastName` VARCHAR(50) NOT NULL, 
  `Nationality` VARCHAR(50), 
  `Gender` VARCHAR(1) DEFAULT 'M', 
  `YearOfBirth` INTEGER DEFAULT 0, 
  `YearOfDeath` INTEGER DEFAULT 0, 
  `Details` LONGTEXT, 
  `ArtistLink` VARCHAR(255), 
  INDEX (`ArtistID`), 
  INDEX (`LastName`), 
  PRIMARY KEY (`ArtistID`)
) ENGINE=innodb DEFAULT CHARSET=utf8;

SET autocommit=1;

#
# Dumping data for table 'Artists'
#

INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (1, 'Pablo', 'Picasso', 'Spain', 'M', 1881, 1973, 'Pablo Diego José Francisco de Paula Juan Nepomuceno María de los Remedios Cipriano de la Santísima Trinidad Ruiz y Picasso known as Pablo Ruiz Picasso was a Spanish painter, draughtsman, and sculptor who lived most of his life in France. He is widely known for co-founding the Cubist movement and for the wide variety of styles that he helped develop and explore. Among his most famous works are the proto-Cubist Les Demoiselles d\'Avignon (1907) and Guernica (1937), a portrayal of the German bombing of Guernica during the Spanish Civil War.', 'http://en.wikipedia.org/wiki/Picasso');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (2, 'Henri', 'Matisse', 'France', 'M', 1869, 1954, 'Henri Matisse was a French artist, known for his use of colour and his fluid and original draughtsmanship. He was a draughtsman, printmaker, and sculptor, but is known primarily as a painter. Matisse is commonly regarded, along with Picasso and Marcel Duchamp, as one of the three artists who helped to define the revolutionary developments in the plastic arts in the opening decades of the 20th century, responsible for significant developments in painting and sculpture. Although he was initially labelled a Fauve (wild beast), by the 1920s he was increasingly hailed as an upholder of the classical tradition in French painting. His mastery of the expressive language of colour and drawing, displayed in a body of work spanning over a half-century, won him recognition as a leading figure in modern art', 'http://en.wikipedia.org/wiki/Matisse');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (5, 'Jacques-Louis', 'David', 'France', 'M', 1748, 1825, 'Jacques-Louis David was a French painter in the Neoclassical style, considered to be the preeminent painter of the era. In the 1780s his cerebral brand of history painting marked a change in taste away from Rococo frivolity toward a classical austerity and severity, heightened feeling chiming with the moral climate of the final years of the Ancien Régime.\r\nDavid later became an active supporter of the French Revolution and friend of Maximilien Robespierre (1758–1794), and was effectively a dictator of the arts under the French Republic. Imprisoned after Robespierre\'s fall from power, he aligned himself with yet another political regime upon his release, that of Napoleon I. It was at this time that he developed his Empire style, notable for its use of warm Venetian colours. David had a huge number of pupils, making him the strongest influence in French art of the early 19th century, especially academic Salon painting.', 'http://en.wikipedia.org/wiki/Jacques-Louis_David');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (6, 'Jean-Auguste-Dominique', 'Ingres', 'France', 'M', 1780, 1867, 'Jean-Auguste-Dominique Ingres was a French Neoclassical painter. Although he considered himself to be a painter of history in the tradition of Nicolas Poussin and Jacques-Louis David, by the end of his life it was Ingres\'s portraits, both painted and drawn, that were recognized as his greatest legacy.', 'http://en.wikipedia.org/wiki/Ingres');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (7, 'Eugene', 'Delacroix', 'France', 'M', 1798, 1863, 'Eugène Delacroix was a French Romantic artist regarded from the outset of his career as the leader of the French Romantic school. Delacroix\'s use of expressive brushstrokes and his study of the optical effects of colour profoundly shaped the work of the Impressionists, while his passion for the exotic inspired the artists of the Symbolist movement. A fine lithographer, Delacroix illustrated various works of William Shakespeare, the Scottish writer Walter Scott and the German writer Johann Wolfgang von Goethe.', 'http://en.wikipedia.org/wiki/Eug%C3%A8ne_Delacroix');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (8, 'Francisco', 'Goya', 'Spain', 'M', 1746, 1828, 'Francisco José de Goya y Lucientes was a Spanish romantic painter and printmaker regarded both as the last of the Old Masters and the first of the moderns. Goya was a court painter to the Spanish Crown, and through his works was both a commentator on and chronicler of his era. The subversive and imaginative element in his art, as well as his bold handling of paint, provided a model for the work of later generations of artists, notably Manet, Picasso and Francis Bacon.', 'http://en.wikipedia.org/wiki/Goya');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (10, 'Gustave', 'Courbet', 'France', 'M', 1818, 1877, 'Jean Désiré Gustave Courbet was a French painter who led the Realist movement in 19th-century French painting. The Realist movement bridged the Romantic movement (characterized by the paintings of Théodore Géricault and Eugène Delacroix), with the Barbizon School and the Impressionists. Courbet occupies an important place in 19th century French painting as an innovator and as an artist willing to make bold social commentary in his work.', 'http://en.wikipedia.org/wiki/Courbet');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (12, 'Edouard', 'Manet', 'France', 'M', 1832, 1883, 'Édouard Manet was a French painter. One of the first 19th-century artists to approach modern-life subjects, he was a pivotal figure in the transition from Realism to Impressionism.', 'http://en.wikipedia.org/wiki/Manet');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (13, 'James Abbott', 'Whistler', 'USA', 'M', 1834, 1903, 'James Abbott McNeill Whistler was an American-born, British-based artist. Averse to sentimentality and moral allusion in painting, he was a leading proponent of the credo \"art for art\'s sake\". His famous signature for his paintings was in the shape of a stylized butterfly possessing a long stinger for a tail. The symbol was apt, for it combined both aspects of his personality—his art was characterized by a subtle delicacy, while his public persona was combative. Finding a parallel between painting and music, Whistler titled many of his paintings \"arrangements\", \"harmonies\", and \"nocturnes\", emphasizing the primacy of tonal harmony. His most famous painting is Whistler\'s Mother (1871), the revered and oft parodied portrait of motherhood. Whistler influenced the art world and the broader culture of his time with his artistic theories and his friendships with leading artists and writers.', 'http://en.wikipedia.org/wiki/James_Abbott_McNeill_Whistler');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (14, 'Pierre Auguste', 'Renoir', 'France', 'M', 1841, 1919, 'Pierre-Auguste Renoir was a French artist who was a leading painter in the development of the Impressionist style. As a celebrator of beauty, and especially feminine sensuality, it has been said that \"Renoir is the final representative of a tradition which runs directly from Rubens to Watteau.\"', 'http://en.wikipedia.org/wiki/Renoir');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (15, 'Edgar', 'Degas', 'France', 'M', 1834, 1917, 'Edgar Degas, born Hilaire-Germain-Edgar De Gas, was a French artist famous for his work in painting, sculpture, printmaking and drawing. He is regarded as one of the founders of Impressionism although he rejected the term, and preferred to be called a realist. A superb draughtsman, he is especially identified with the subject of the dance, and over half of his works depict dancers. These display his mastery in the depiction of movement, as do his racecourse subjects and female nudes. His portraits are notable for their psychological complexity and depiction of human isolation.', 'http://en.wikipedia.org/wiki/Degas');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (16, 'Mary', 'Cassatt', 'USA', 'F', 1845, 1926, 'Mary Stevenson Cassatt was an American painter and printmaker. She lived much of her adult life in France, where she first befriended Edgar Degas and later exhibited among the Impressionists. Cassatt often created images of the social and private lives of women, with particular emphasis on the intimate bonds between mothers and children.', 'http://en.wikipedia.org/wiki/Mary_Cassatt');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (17, 'Claude', 'Monet', 'France', 'M', 1840, 1926, 'Claude Monet was a founder of French impressionist painting, and the most consistent and prolific practitioner of the movement\'s philosophy of expressing one\'s perceptions before nature, especially as applied to plein-air landscape painting. The term Impressionism is derived from the title of his painting Impression, Sunrise (Impression, soleil levant).', 'http://en.wikipedia.org/wiki/Claude_Monet');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (18, 'Paul', 'Gauguin', 'France', 'M', 1848, 1903, 'Eugène Henri Paul Gauguin was a leading French Post-Impressionist artist. He was an important figure in the Symbolist movement as a painter, sculptor, print-maker, ceramist, and writer. His bold experimentation with coloring led directly to the Synthetist style of modern art while his expression of the inherent meaning of the subjects in his paintings, under the influence of the cloisonnist style, paved the way to Primitivism and the return to the pastoral. He was also an influential proponent of wood engraving and woodcuts as art forms.', 'http://en.wikipedia.org/wiki/Gauguin');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (19, 'Vincent', 'Van Gogh', 'Netherlands', 'M', 1853, 1890, 'Vincent Willem van Gogh was a Dutch post-Impressionist painter whose work, notable for its rough beauty, emotional honesty, and bold color, had a far-reaching influence on 20th-century art. After years of painful anxiety and frequent bouts of mental illness, he died at the age of 37 from a self-inflicted gunshot wound. His work was then known to only a handful of people and appreciated by fewer still.', 'http://en.wikipedia.org/wiki/Van_Gogh');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (20, 'Georges', 'Seurat', 'France', 'M', 1859, 1891, 'Georges-Pierre Seurat was a French Post-Impressionist painter and draftsman. He is noted for his innovative use of drawing media and for devising a technique of painting known as pointillism. His large-scale work A Sunday Afternoon on the Island of La Grande Jatte (1884–1886), Seurat\'s most famous painting, altered the direction of modern art by initiating Neo-impressionism, and is one of the icons of 19th century painting.', 'http://en.wikipedia.org/wiki/Seurat');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (21, 'Paul', 'Cezanne', 'France', 'M', 1839, 1906, 'Paul Cézanne was a French artist and Post-Impressionist painter whose work laid the foundations of the transition from the 19th century conception of artistic endeavour to a new and radically different world of art in the 20th century. Cézanne can be said to form the bridge between late 19th century Impressionism and the early 20th century\'s new line of artistic enquiry, Cubism. The line attributed to both Matisse and Picasso that Cézanne \"is the father of us all\" cannot be easily dismissed.', 'http://en.wikipedia.org/wiki/C%C3%A9zanne');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (24, 'Edvard', 'Munch', 'Norway', 'M', 1863, 1944, 'Edvard Munch was a Norwegian Symbolist painter, printmaker and an important forerunner of expressionist art. His best-known composition, The Scream, is part of a series The Frieze of Life, in which Munch explored the themes of love, fear, death, melancholia, and anxiety.', 'http://en.wikipedia.org/wiki/Edvard_Munch');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (28, 'Henri', 'Toulouse-Lautrec', 'France', 'M', 1864, 1901, 'Henri Marie Raymond de Toulouse-Lautrec-Monfa or simply Henri de Toulouse-Lautrec was a French painter, printmaker, draughtsman, and illustrator, whose immersion in the colourful and theatrical life of fin de siècle Paris yielded an œuvre of exciting, elegant and provocative images of the modern and sometimes decadent life of those times. Toulouse-Lautrec is known along with Cézanne, Van Gogh, and Gauguin as one of the greatest painters of the Post-Impressionist period. In a 2005 auction at Christie\'s auction house a new record was set when \"La blanchisseuse\", an early painting of a young laundress, sold for $22.4 million U.S.', 'http://en.wikipedia.org/wiki/Toulouse-Lautrec');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (29, 'Gustav', 'Klimt', 'Austria', 'M', 1862, 1918, 'Gustav Klimt was an Austrian Symbolist painter and one of the most prominent members of the Vienna Secession movement. His major works include paintings, murals, sketches, and other art objects. Klimt\'s primary subject was the female body, and his works are marked by a frank eroticism—nowhere is this more apparent than in his numerous drawings in pencil', 'http://en.wikipedia.org/wiki/Klimt');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (32, 'Andre', 'Derain', 'France', 'M', 1880, 1919, 'André Derain  was a French artist, painter, sculptor and co-founder of Fauvism with Henri Matisse', 'http://en.wikipedia.org/wiki/Andr%C3%A9_Derain');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (40, 'Vasily', 'Kandinsky', 'Russia', 'M', 1866, 1944, 'Wassily Wassilyevich Kandinsky was a Russian painter and art theorist. He is credited with painting the first purely-abstract works. Born in Moscow, Kandinsky spent his childhood in Odessa. He enrolled at the University of Moscow, studying law and economics. Successful in his profession—he was offered a professorship (chair of Roman Law) at the University of Dorpat—he began painting studies (life-drawing, sketching and anatomy) at the age of 30.', 'http://en.wikipedia.org/wiki/Kandinsky');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (41, 'Giacomo', 'Balla', 'Italy', 'M', 1871, 1958, 'Giacomo Balla was an Italian painter.', 'http://en.wikipedia.org/wiki/Giacomo_Balla');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (45, 'Salvidor', 'Dali', 'Spain', 'M', 1904, 1989, 'Salvador Domènec Felip Jacint Dalí i Domènech, Marquis de Púbol, commonly known as Salvador Dalí was a prominent Spanish Catalan surrealist painter born in Figueres.', 'http://en.wikipedia.org/wiki/Salvador_Dal%C3%AD');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (49, 'Georgia', 'O\'Keefe', 'USA', 'F', 1887, 1986, 'Georgia Totto O\'Keeffe was an American artist. Born near Sun Prairie, Wisconsin, O\'Keeffe first came to the attention of the New York art community in 1916, several decades after women had gained access to art training in America’s colleges and universities, and before any of its women artists were well known or highly celebrated. Within a decade, she had distinguished herself as one of America\'s most important modern artists, a position she maintained throughout her life. As a result, O’Keeffe not only carved out a significant place for women painters in an area of the American art community that had been exclusive to and is still dominated by men, but also she had become one of America’s most celebrated cultural icons well before her death at age 98 in 1986.', 'http://en.wikipedia.org/wiki/Georgia_O%27Keefe');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (60, 'Paul', 'Klee', 'Switzerland', 'M', 1879, 1940, 'Paul Klee was born in Münchenbuchsee, Switzerland, and is considered both a German and a Swiss painter. His highly individual style was influenced by movements in art that included expressionism, cubism, and surrealism. He was, as well, a student of orientalism. Klee was a natural draftsman who experimented with and eventually mastered color theory, and wrote extensively about it; his lectures Writings on Form and Design Theory (Schriften zur Form und Gestaltungslehre), published in English as the Paul Klee Notebooks, are considered so important for modern art that they are compared to the importance that Leonardo da Vinci\'s A Treatise on Painting had for Renaissance. He and his colleague, the Russian painter Wassily Kandinsky, both taught at the German Bauhaus school of art, design and architecture. His works reflect his dry humour and his sometimes childlike perspective, his personal moods and beliefs, and his musicality.', 'http://en.wikipedia.org/wiki/Paul_Klee');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (63, 'Henri', 'Rousseau', 'France', 'M', 1844, 1910, 'Henri Julien Félix Rousseau was a French Post-Impressionist painter in the Naive or Primitive manner. He was also known as Le Douanier (the customs officer), a humorous description of his occupation as a tax collector. Ridiculed during his life, he came to be recognized as a self-taught genius whose works are of high artistic quality.', 'http://en.wikipedia.org/wiki/Henri_Rousseau');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (64, 'Marc', 'Chagall', 'Russia', 'M', 1887, 1985, 'Marc Chagall was a Belorussian-French artist associated with several major artistic styles and one of the most successful artists of the 20th century. He was an early modernist, and created works in virtually every artistic medium, including painting, book illustrations, stained glass, stage sets, ceramic, tapestries and fine art prints.', 'http://en.wikipedia.org/wiki/Chagall');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (73, 'Piet', 'Mondrian', 'Netherlands', 'M', 1872, 1944, 'Pieter Cornelis \"Piet\" Mondriaan, after 1912 Mondrian, was a Dutch painter. He was an important contributor to the De Stijl art movement and group, which was founded by Theo van Doesburg. He evolved a non-representational form which he termed Neo-Plasticism. This consisted of white ground, upon which was painted a grid of vertical and horizontal black lines and the three primary colors.', 'http://en.wikipedia.org/wiki/Piet_Mondrian');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (85, 'Jackson', 'Pollock', 'USA', 'M', 1912, 1959, 'Paul Jackson Pollock , known as Jackson Pollock, was an influential American painter and a major figure in the abstract expressionist movement. During his lifetime, Pollock enjoyed considerable fame and notoriety. He was regarded as a mostly reclusive artist. He had a volatile personality, and struggled with alcoholism for most of his life. In 1945, he married the artist Lee Krasner, who became an important influence on his career and on his legacy.', 'http://en.wikipedia.org/wiki/Jackson_pollock');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (92, 'Filippo', 'Lippi', 'Italy', 'M', 1406, 1469, 'Filippo Lippi, also called Lippo Lippi, was an Italian painter of the Italian Quattrocento (15th century).', 'http://en.wikipedia.org/wiki/Filippo_Lippi');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (93, 'Piero della', 'Francesca', 'Italy', 'M', 1412, 1492, '<strong>Piero della Francesca</strong> was a painter of the Early Renaissance. As testified by Giorgio Vasari in his <em>Lives of the Artists</em>, to contemporaries he was also known as a mathematician and geometer. Nowadays Piero della Francesca is chiefly appreciated for his art. His painting was characterized by its serene humanism, its use of geometric forms and perspective. His most famous work is the cycle of frescoes \"The Legend of the True Cross\" in the church of San Francesco in the Tuscan town of Arezzo.', 'http://en.wikipedia.org/wiki/Piero_della_Francesca');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (94, 'Andrea', 'Mantegna', 'Italy', 'M', 1431, 1506, '<strong>Andrea Mantegna</strong> was an Italian painter, a student of Roman archeology, and son in law of Jacopo Bellini. Like other artists of the time, Mantegna experimented with perspective, e.g., by lowering the horizon in order to create a sense of greater monumentality. His flinty, metallic landscapes and somewhat stony figures give evidence of a fundamentally sculptural approach to painting. He also led a workshop that was the leading producer of prints in Venice before 1500.', 'http://en.wikipedia.org/wiki/Andrea_Mantegna');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (95, 'Sandro', 'Botticelli', 'Italy', 'M', 1445, 1510, 'Alessandro di Mariano di Vanni Filipepi, better known as <strong>Sandro Botticelli</strong> was an Italian painter of the Early Renaissance. He belonged to the Florentine school under the patronage of Lorenzo de\' Medici, a movement that Giorgio Vasari would characterize less than a hundred years later as a \"golden age\", a thought, suitably enough, he expressed at the head of his Vita of Botticelli. Botticelli\'s posthumous reputation suffered until the late 19th century; since then his work has been seen to represent the linear grace of Early Renaissance painting. Among his best known works are The Birth of Venus and Primavera.', 'http://en.wikipedia.org/wiki/Sandro_Botticelli');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (96, 'Pietro', 'Perugino', 'Italy', 'M', 1446, 1524, '<strong>Pietro Perugino</strong>, born Pietro Vannucci, was an Italian Renaissance painter of the Umbrian school, who developed some of the qualities that found classic expression in the High Renaissance. Raphael was his most famous pupil.', 'http://en.wikipedia.org/wiki/Pietro_Perugino');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (97, 'Leonardo', 'da Vinci', 'Italy', 'M', 1452, 1519, '<strong>Leonardo di ser Piero da Vinci</strong> was an Italian Renaissance polymath: painter, sculptor, architect, musician, mathematician, engineer, inventor, anatomist, geologist, cartographer, botanist, and writer. His genius, perhaps more than that of any other figure, epitomized the Renaissance humanist ideal. Leonardo has often been described as the archetype of the Renaissance Man, a man of \"unquenchable curiosity\" and \"feverishly inventive imagination\". He is widely considered to be one of the greatest painters of all time and perhaps the most diversely talented person ever to have lived. According to art historian Helen Gardner, the scope and depth of his interests were without precedent and \"his mind and personality seem to us superhuman, the man himself mysterious and remote\". Marco Rosci states that while there is much speculation about Leonardo, his vision of the world is essentially logical rather than mysterious, and that the empirical methods he employed were unusual for his time.', 'http://en.wikipedia.org/wiki/Leonardo_da_Vinci');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (98, NULL, 'Michelangelo', 'Italy', 'M', 1475, 1564, '<strong>Michelangelo di Lodovico Buonarroti Simoni</strong> commonly known as Michelangelo, was an Italian sculptor, painter, architect, poet, and engineer of the High Renaissance who exerted an unparalleled influence on the development of Western art. Despite making few forays beyond the arts, his versatility in the disciplines he took up was of such a high order that he is often considered a contender for the title of the archetypal Renaissance man, along with his fellow Italian Leonardo da Vinci. Michelangelo was considered the greatest living artist in his lifetime, and ever since then he has been held to be one of the greatest artists of all time. A number of his works in painting, sculpture, and architecture rank among the most famous in existence. His output in every field during his long life was prodigious; when the sheer volume of correspondence, sketches, and reminiscences that survive is also taken into account, he is the best-documented artist of the 16th century.', 'http://en.wikipedia.org/wiki/Michelangelo');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (99, NULL, 'Raphael', 'Italy', 'M', 1483, 1520, 'Raffaello Sanzio da Urbino, better known simply as <strong>Raphael</strong>, was an Italian painter and architect of the High Renaissance. His work is admired for its clarity of form and ease of composition and for its visual achievement of the Neoplatonic ideal of human grandeur. Together with Michelangelo and Leonardo da Vinci, he forms the traditional trinity of great masters of that period.', 'http://en.wikipedia.org/wiki/Raphael');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (100, NULL, 'Titian', 'Italy', 'M', 1488, 1576, '<strong>Tiziano Vecelli</strong> known in English as <strong>Titian</strong> was an Italian painter, the most important member of the 16th-century Venetian school. He was born in Pieve di Cadore, near Belluno (in Veneto), in the Republic of Venice. During his lifetime he was often called da Cadore, taken from the place of his birth. During the course of his long life, Titian\'s artistic manner changed drastically[4] but he retained a lifelong interest in color. Although his mature works may not contain the vivid, luminous tints of his early pieces, their loose brushwork and subtlety of polychromatic modulations are without precedent in the history of Western art.', 'http://en.wikipedia.org/wiki/Titian');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (101, NULL, 'Caravaggio', 'Italy', 'M', 1571, 1610, '<strong>Michelangelo Merisi da Caravaggio</strong> was an Italian artist active in Rome, Naples, Malta, and Sicily between 1593 and 1610. His paintings, which combine a realistic observation of the human state, both physical and emotional, with a dramatic use of lighting, had a formative influence on the Baroque school of painting.', 'http://en.wikipedia.org/wiki/Caravaggio');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (102, 'Peter Paul', 'Rubens', 'Belgium', 'M', 1577, 1640, 'Sir Peter Paul Rubens was a German-born Flemish Baroque painter, and a proponent of an extravagant Baroque style that emphasised movement, colour, and sensuality. He is well known for his Counter-Reformation altarpieces, portraits, landscapes, and history paintings of mythological and allegorical subjects.', 'http://en.wikipedia.org/wiki/Peter_Paul_Rubens');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (103, 'Anthony van', 'Dyck', 'Belgium', 'M', 1599, 1641, '<strong>Sir Anthony van Dyck</strong> was a Flemish Baroque artist who became the leading court painter in England. He is most famous for his portraits of Charles I of England and his family and court, painted with a relaxed elegance that was to be the dominant influence on English portrait-painting for the next 150 years. He also painted biblical and mythological subjects, displayed outstanding facility as a draftsman, and was an important innovator in watercolour and etching.', 'http://en.wikipedia.org/wiki/Anthony_van_Dyck');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (104, 'Diego', 'Velázquez', 'Spain', 'M', 1599, 1660, '<strong>Diego Rodríguez de Silva y Velázquez</strong> was a Spanish painter who was the leading artist in the court of King Philip IV. He was an individualistic artist of the contemporary Baroque period, important as a portrait artist. In addition to numerous renditions of scenes of historical and cultural significance, he painted scores of portraits of the Spanish royal family, other notable European figures, and commoners.', 'http://en.wikipedia.org/wiki/Diego_Vel%C3%A1zquez');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (105, NULL, 'Rembrandt', 'Netherlands', 'M', 1606, 1669, '<strong>Rembrandt Harmenszoon van Rijn</strong> was a Dutch painter and etcher. He is generally considered one of the greatest painters and printmakers in European art history and the most important in Dutch history. His contributions to art came in a period of great wealth and cultural achievement that historians call the Dutch Golden Age when Dutch Golden Age painting, although in many ways antithetical to the Baroque style that dominated Europe, was extremely prolific and innovative.', 'http://en.wikipedia.org/wiki/Rembrandt');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (106, 'Jan', 'Vermeer', 'Netherlands', 'M', 1632, 1675, '<strong>Jan Vermeer</strong> was a Dutch painter who specialized in domestic interior scenes of middle-class life. Vermeer was a moderately successful provincial genre painter in his lifetime. He seems never to have been particularly wealthy, leaving his wife and children in debt at his death, perhaps because he produced relatively few paintings. Vermeer worked slowly and with great care, using bright colours and sometimes expensive pigments, with a preference for cornflower blue and yellow. He is particularly renowned for his masterly treatment and use of light in his work.', 'http://en.wikipedia.org/wiki/Johannes_Vermeer');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (107, 'Francois', 'Boucher', 'France', 'M', 1703, 1770, 'Possibly the most popular 18th century artist, <strong>Francois Boucher</strong> was a French painter in the Rococo style. When he was 17 years old, Boucher was apprenticed for a short time to the French painter Francois Lemoyne, and then to the engraver Jean-Francois Cars. After three years of work and artistic study, Boucher won the Grand Prix de Rome, a scholarship for artistic study, allowing him to travel to Italy and further his study in art. Upon his return to France, he was accepted into the Royal Academy of Painting and Sculpture, and three years later became a faculty member.', 'http://en.wikipedia.org/wiki/Fran%C3%A7ois_Boucher');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (108, 'Jean-Baptiste-Simeon', 'Chardin', 'France', 'M', 1699, 1779, '<strong>Jean-Baptiste-Siméon Chardin</strong> was an 18th-century French painter. He is considered a master of still life, and is also noted for his genre paintings which depict kitchen maids, children, and domestic activities. Carefully balanced composition, soft diffusion of light, and granular impasto characterize his work.', 'http://en.wikipedia.org/wiki/Jean-Baptiste-Sim%C3%A9on_Chardin');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (109, 'Joshua', 'Reynolds', 'England', 'M', 1740, 1790, '<strong>Sir Joshua Reynolds</strong> was an influential eighteenth-century English painter, specialising in portraits and promoting the \"Grand Style\" in painting which depended on idealization of the imperfect. He was one of the founders and first president of the Royal Academy, and was knighted by George III in 1769.', 'http://en.wikipedia.org/wiki/Joshua_Reynolds');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (110, 'Thomas', 'Gainsborough', 'England', 'M', 1737, 1788, '<strong>Thomas Gainsborough</strong> was an English portrait and landscape painter. He is credited as the originator of the 18th century British landscape school.', 'http://en.wikipedia.org/wiki/Thomas_Gainsborough');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (111, 'Artemisia', 'Gentileschi', 'Italy', 'F', 1593, 1656, '<strong>Artemisia Gentileschi</strong> was an Italian Baroque painter, today considered one of the most accomplished painters in the generation after Caravaggio. In an era when female painters were not easily accepted by the artistic community or patrons, she was the first female painter to become a member of the Accademia di Arte del Disegno in Florence. She painted many pictures of strong and suffering women from myth and the Bible – victims, suicides, warriors – and made a speciality of the Judith story.  That she was a woman painting in the 17th century and that she was raped herself and participated in prosecuting the rapist long overshadowed her achievements as an artist. For many years she was regarded as a curiosity. Today she is regarded as one of the most progressive and expressionist painters of her generation.', 'http://en.wikipedia.org/wiki/Artemisia_Gentileschi');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (112, 'Judith', 'Leyster', 'Netherlands', 'F', 1609, 1660, '<strong>Judith Jans Leyster (also Leijster)</strong> was a Dutch Golden Age painter. She was one of three significant women artists in Dutch Golden Age painting; the other two, Rachel Ruysch and Maria van Oosterwijk, were specialized painters of flower still-lifes, while Leyster painted genre works, a few portraits, and a single still life. The number of surviving works attributed to her varies between fewer than 20 and about 35. She largely gave up painting after her marriage, which produced five children.', 'http://en.wikipedia.org/wiki/Judith_Leyster');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (113, 'Louise Élisabeth', 'Lebrun', 'France', 'F', 1755, 1842, '<strong>Louise Élisabeth Vigée Le Brun</strong> also known as Madame Lebrun, was a French painter, and is recognized as the most important female painter of the 18th century. Her style is generally considered Rococo and shows interest in the subject of neoclassical painting. Vigée Le Brun cannot be considered a pure Neoclassist, however, in that she creates mostly portraits in Neoclassical dress.', 'http://en.wikipedia.org/wiki/Elisabeth_Vigee-Lebrun');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (114, NULL, 'Giotto', 'Italy', 'M', 1266, 1337, '<strong>Giotto di Bondone</strong> better known simply as Giotto, was an Italian painter and architect from Florence in the late Middle Ages. He is generally considered the first in a line of great artists who contributed to the Italian Renaissance.', 'https://en.wikipedia.org/wiki/Giotto');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (115, 'Jan', 'van Eyck', 'Belgium', 'M', 1390, 1441, '<strong>Jan van Eyck</strong> was a Flemish painter active in Bruges and is generally considered one of the most significant Northern European painters of the 15th century. The few surviving records indicate that he was born around 1390, most likely in Maaseik. Outside of works completed with his brother Hubert van Eyck and those ascribed to Hand G —believed to be Jan— of the Turin-Milan Hours illuminated manuscript, only about 23 surviving works are confidently attributed to him, of which ten, including the Ghent altarpiece, are signed and dated.', 'http://en.wikipedia.org/wiki/Jan_van_Eyck');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (116, 'Albrecht', 'Dürer', 'Germany', 'M', 1471, 1528, '<strong>Albrecht Dürer </strong> was a German painter, engraver, printmaker, mathematician, and theorist from Nuremberg. His high-quality woodcuts established his reputation and influence across Europe when he was still in his twenties, and he has been conventionally regarded as the greatest artist of the Northern Renaissance ever since. His vast body of work includes altarpieces and religious works, numerous portraits and self-portraits, and copper engravings. The woodcuts, such as the Apocalypse series (1498), retain a more Gothic flavour than the rest of his work. His well-known prints include the Knight, Death, and the Devil (1513), Saint Jerome in his Study (1514) and Melencolia I (1514), which has been the subject of extensive analysis and interpretation. His watercolours also mark him as one of the first European landscape artists, while his ambitious woodcuts revolutionized the potential of that medium. Dürer\'s introduction of classical motifs into Northern art, through his knowledge of Italian artists and German humanists, has secured his reputation as one of the most important figures of the Northern Renaissance. This is reinforced by his theoretical treatises, which involve principles of mathematics, perspective and ideal proportions.', 'http://en.wikipedia.org/wiki/Albrecht_D%C3%Bcrer');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (117, 'Hieronymus', 'Bosch', 'Netherlands', 'M', 1450, 1516, '<strong>Hieronymus Bosch</strong>was an Early Netherlandish painter. His work is known for its use of fantastic imagery to illustrate moral and religious concepts and narratives.', 'http://en.wikipedia.org/wiki/Hieronymus_Bosch');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (118, 'Pieter', 'Bruegel the Elder', 'Netherlands', 'M', 1525, 1569, '<strong>Pieter Bruegel (Brueghel) the Elder</strong> was a Flemish Renaissance painter and printmaker known for his landscapes and peasant scenes (so called genre painting). He is sometimes referred to as the \"Peasant Bruegel.\" From 1559 he dropped the \'h\' from his name and signed his paintings as Bruegel.', 'http://en.wikipedia.org/wiki/Pieter_Bruegel_the_Elder');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (120, 'Agnolo', 'Bronzino', 'Italy', 'M', 1503, 1572, 'One of the greatest painters of the sixteenth century, Agnolo di Cosimo Tori, known as <strong>Bronzino</strong>, embodied the Mannerist style in the years of the government of Cosimo I de’ Medici.', 'http://en.wikipedia.org/wiki/Bronzino');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (121, 'El', 'Greco', 'Greece', 'M', 1514, 1614, '<strong>El Greco</strong>, born Doménikos Theotokópoulos,  was a painter, sculptor and architect of the Spanish Renaissance. \"El Greco\" (The Greek) was a nickname,a reference to his national Greek origin. El Greco\'s dramatic and expressionistic style was met with puzzlement by his contemporaries but found appreciation in the 20th century. El Greco is regarded as a precursor of both Expressionism and Cubism.', 'http://en.wikipedia.org/wiki/El_Greco');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (123, 'Frans', 'Hals', 'Netherlands', 'M', 1582, 1666, '<strong>Frans Hals the Elder</strong> was a Dutch Golden Age portrait painter who lived and worked in Haarlem. He is notable for his loose painterly brushwork, and he helped introduce this lively style of painting into Dutch art. Hals played an important role in the evolution of 17th-century group portraiture.', 'https://en.wikipedia.org/wiki/Frans_Hals');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (124, 'Jan', 'Steen', 'Netherlands', 'M', 1626, 1679, 'Jan Havickszoon Steen was a Dutch genre painter of the 17th century (also known as the Dutch Golden Age). His works are known for their psychological insight, sense of humour and abundance of colour', 'https://en.wikipedia.org/wiki/Jan_Steen');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (125, 'Jan', 'Kruseman', 'Netherlands', 'M', 1804, 1862, 'Jan Adam Kruseman (1804-1862) of Haarlem was apprenticed to his uncle Cornelis Kruseman. He later studied at Brussels and Paris. In 1834-1836, he made a series of journeys to Germany, England and Scotland. For a while, he lived in Driebergen, before returning to Haarlem in 1858. Kruseman painted historical, biblical and genre scenes, although mainly portraits. In all he received around five hundred commissions from aristocrats and wealthy commoners for portraits.', 'https://en.wikipedia.org/wiki/Jan_Adam_Kruseman');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (126, 'Pieter de', 'Hooch', 'Netherlands', 'M', 1629, 1684, 'Pieter de Hooch was a Dutch Golden Age painter famous for his genre works of quiet domestic scenes with an open doorway. He was a contemporary of Jan Vermeer in the Delft Guild of St. Luke, with whom his work shares themes and style.', 'https://en.wikipedia.org/wiki/Pieter_de_Hooch');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (127, 'Jacob van', 'Ruisdael', 'Netherlands', 'M', 1628, 1682, 'The Haarlem-born painter Jacob van Ruisdael (ca. 1628-1682) began to paint at an early age. His first work dates from 1646. Ruisdael probably had lessons from his father, but his uncle, the artist Salomon van Ruysdael, must also have been a great influence on the young painter. As well as being a painter, Ruisdael was also a doctor. He painted not only woodland landscapes with strong, central motifs such as ruins, watermills and oaks, but also cityscapes and seascapes. Ruisdael\'s compositions are often more imposing than reality. His \'Bentheim Castle\' and \'Windmill at Wijk bij Duurstede\' are good examples of this.', 'https://en.wikipedia.org/wiki/Jacob_van_Ruisdael');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (128, 'Anton', 'Mauve', 'Netherlands', 'M', 1838, 1888, 'Anthonij (Anton) Rudolf Mauve was a Dutch realist painter who was a leading member of the Hague School. He signed his paintings \'A. Mauve\' or with a monogrammed \'A.M.\'. A master colorist, he was a very significant early influence on his cousin-in-law Vincent van Gogh. Most of Mauve\'s work depicts people and animals in outdoor settings. In his Morning Ride in the Rijksmuseum, for example, fashionable equestrians at the seacoast are seen riding away from the viewer. An unconventional detail, horse droppings in the foreground, attests his commitment to realism.', 'https://en.wikipedia.org/wiki/Anton_Mauve');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (129, 'Lawrence', 'Alma-Tadema', 'Netherlands', 'M', 1836, 1912, 'Sir Lawrence Alma-Tadema (born Lourens Alma Tadema) was a Dutch painter of special British denizenship. Born in Dronrijp, the Netherlands, and trained at the Royal Academy of Antwerp, Belgium, he settled in England in 1870 and spent the rest of his life there. A classical-subject painter, he became famous for his depictions of the luxury and decadence of the Roman Empire, with languorous figures set in fabulous marbled interiors or against a backdrop of dazzling blue Mediterranean Sea and sky. Though admired during his lifetime for his draftsmanship and depictions of Classical antiquity, his work fell into disrepute after his death, and only since the 1960s has it been re-evaluated for its importance within nineteenth-century English art.', 'https://en.wikipedia.org/wiki/Lawrence_Alma-Tadema');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (130, 'Thérèse', 'Schwartze', 'Netherlands', 'F', 1851, 1918, 'Thérèse Schwartze was born on 20 December 1851 in Amsterdam in the Netherlands. She was the daughter of the painter Johan Georg Schwartze, who grew up in Philadelphia and trained in Düsseldorf. Schwartze received her first training from her father, before studying for a year at the Rijksacademie van Beeldende Kunsten. She then travelled to Munich and studied under Gabriel Max and Franz von Lenbach. In 1879 she went to Paris to continue her studies under Jean-Jacques Henner. When she returned to Amsterdam she became a member of Arti et Amicitiae.', 'https://en.wikipedia.org/wiki/Th%C3%A9r%C3%A8se_Schwartze');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (131, NULL, 'Canaletto', 'Italy', 'M', 1697, 1768, 'Giovanni Antonio Canal, better known as Canaletto, was an Italian painter of landscapes of Venice. He was also an important printmaker in etching. He was the son of the painter Bernardo Canal, he visited England between 1746–56 and he is famous for his urban landscapes of Venice. He is very famous for his scenes, usually associated with \"evocative views of the city\".', 'https://en.wikipedia.org/wiki/Canaletto');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (132, 'Nicolas', 'Poussin', 'France', 'M', 1594, 1665, 'Nicolas Poussin was the leading painter of the classical French Baroque style, although he spent most of his working life in Rome. His work is characterized by clarity, logic, and order, and favors line over color. Until the 20th century he remained a major inspiration for such classically oriented artists as Jacques-Louis David, Jean-Auguste-Dominique Ingres and Paul Cézanne. He worked in Rome for a circle of leading collectors from there and elsewhere, except for a short period when Cardinal Richelieu ordered him back to France to serve as First Painter to the King. Most of his works are history paintings of religious or mythological subjects that very often have a large landscape element.', 'https://en.wikipedia.org/wiki/Nicolas_Poussin');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (133, 'Ferdinand Georg', 'Waldmüller', 'Austria', 'M', 1793, 1865, 'Ferdinand Georg Waldmüller (1793–1865) is considered the most important Austrian artist of the 19th century. On the one hand, he produced outstanding works in the artistic disciplines prevalent at the time – portraiture, landscape, still life, and genre painting – and, on the other hand, he was always, throughout his life, in search of accomplishment, striding new paths that led the way into the future.', 'https://en.wikipedia.org/wiki/Ferdinand_Georg_Waldm%C3%Bcller');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (134, 'Rogier van der', 'Weyden', 'Netherlands', 'M', 1399, 1464, 'Rogier van der Weyden or Roger de la Pasture was an Early Netherlandish painter. His surviving works consist mainly of religious triptychs, altarpieces and commissioned single and diptych portraits. Although his life was generally uneventful, he was highly successful and internationally famous in his lifetime. His paintings were exported – or taken – to Italy and Spain, and he received commissions from, amongst others, Philip the Good, Netherlandish nobility and foreign princes. By the latter half of the 15th century, he had eclipsed Jan van Eyck in popularity. However his fame lasted only until the 17th century, and largely due to changing taste, he was almost totally forgotten by the mid-18th century. His reputation was slowly rebuilt during the following 200 years; today he is known, with Robert Campin and van Eyck, as the third of the three great Early Flemish artists, and widely as the most influential Northern painter of the 15th century.', 'https://en.wikipedia.org/wiki/Rogier_van_der_Weyden');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (135, 'Giovanni', 'Bellini', 'Italy', 'M', 1430, 1516, 'Giovanni Bellini was an Italian Renaissance painter, probably the best known of the Bellini family of Venetian painters. His father was Jacopo Bellini, his brother was Gentile Bellini, and his brother-in-law was Andrea Mantegna. He is considered to have revolutionized Venetian painting, moving it towards a more sensuous and colouristic style. Through the use of clear, slow-drying oil paints, Giovanni created deep, rich tints and detailed shadings. His sumptuous coloring and fluent, atmospheric landscapes had a great effect on the Venetian painting school, especially on his pupils Giorgione and Titian.', 'https://en.wikipedia.org/wiki/Giovanni_Bellini');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (136, 'Francesco', 'Hayez', 'Italy', 'M', 1791, 1882, 'Francesco Hayez was an Italian painter, the leading artist of Romanticism in mid-19th-century Milan, renowned for his grand historical paintings, political allegories and exceptionally fine portraits.', 'https://en.wikipedia.org/wiki/Francesco_Hayez');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (137, 'Caspar David', 'Friedrich', 'Germany', 'M', 1774, 1840, 'Caspar David Friedrich was a 19th-century German Romantic landscape painter, generally considered the most important German artist of his generation. He is best known for his mid-period allegorical landscapes which typically feature contemplative figures silhouetted against night skies, morning mists, barren trees or Gothic ruins.', 'https://en.wikipedia.org/wiki/Caspar_David_Friedrich');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (138, 'Arnold', 'Böcklin', 'Switzerland', 'M', 1827, 1901, 'Arnold Böcklin was a Swiss symbolist painter.', 'https://en.wikipedia.org/wiki/Arnold_B%C3%B6cklin');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (139, 'John William', 'Waterhouse', 'England', 'M', 1849, 1917, 'John William Waterhouse was an English painter known for working in the Pre-Raphaelite style. He worked several decades after the breakup of the Pre-Raphaelite Brotherhood, which had seen its heyday in the mid-nineteenth century, leading to his sobriquet \"the modern Pre-Raphaelite\". Borrowing stylistic influences not only from the earlier Pre-Raphaelites but also from his contemporaries, the Impressionists, his artworks were known for their depictions of women from both ancient Greek mythology and Arthurian legend.', 'https://en.wikipedia.org/wiki/John_William_Waterhouse');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (140, 'William', 'Bouguereau', 'France', 'M', 1825, 1905, 'William-Adolphe Bouguereau was a French academic painter and traditionalist. In his realistic genre paintings he used mythological themes, making modern interpretations of classical subjects, with an emphasis on the female human body. During his life he enjoyed significant popularity in France and the United States, was given numerous official honors, and received top prices for his work. As the quintessential salon painter of his generation, he was reviled by the Impressionist avant-garde. By the early twentieth century, Bouguereau and his art fell out of favor with the public, due in part to changing tastes. In the 1980s, a revival of interest in figure painting led to a rediscovery of Bouguereau and his work. Throughout the course of his life, Bouguereau executed 822 known finished paintings, although the whereabouts of many are still unknown.', 'https://en.wikipedia.org/wiki/William-Adolphe_Bouguereau');
INSERT INTO `Artists` (`ArtistID`, `FirstName`, `LastName`, `Nationality`, `Gender`, `YearOfBirth`, `YearOfDeath`, `Details`, `ArtistLink`) VALUES (141, 'Agnolo', 'Gaddi', 'Italy', 'M', 1350, 1396, 'Taddeo Gaddi was himself the major pupil of the Florentine master Giotto. Agnolo was an influential and prolific artist who was the last major Florentine painter stylistically descended from Giotto.', 'https://en.wikipedia.org/wiki/Agnolo_Gaddi');
# 78 records

#
# Table structure for table 'CustomerLogon'
#

DROP TABLE IF EXISTS `CustomerLogon`;

CREATE TABLE `CustomerLogon` (
  `CustomerID` INTEGER NOT NULL AUTO_INCREMENT, 
  `UserName` VARCHAR(255), 
  `Pass` VARCHAR(255), 
  `Salt` VARCHAR(255), 
  `State` INTEGER, 
  `DateJoined` DATETIME, 
  `DateLastModified` DATETIME, 
  PRIMARY KEY (`CustomerID`), 
  UNIQUE (`UserName`)
) ENGINE=innodb DEFAULT CHARSET=utf8;

SET autocommit=1;

#
# Dumping data for table 'CustomerLogon'
#

INSERT INTO `CustomerLogon` (`CustomerID`, `UserName`, `Pass`, `Salt`, `State`, `DateJoined`, `DateLastModified`) VALUES (1, 'luisg@embraer.com.br', '81c71e87e09e4310e3b974c79a8f817b', 'HoGiVlunac11vDbbFHpoB0OdDOEkA6Uk', 1, '2012-10-08 00:00:00', '2012-11-15 00:00:00');
INSERT INTO `CustomerLogon` (`CustomerID`, `UserName`, `Pass`, `Salt`, `State`, `DateJoined`, `DateLastModified`) VALUES (2, 'leonekohler@surfeu.de', '5a2b2e0fcff2d5d36bd0f988b1acfe41', 'VubVwUzwUC29gpVff7iZm3Aoe6LWba57', 1, '2012-08-22 00:00:00', '2012-10-15 00:00:00');
INSERT INTO `CustomerLogon` (`CustomerID`, `UserName`, `Pass`, `Salt`, `State`, `DateJoined`, `DateLastModified`) VALUES (3, 'ftremblay@gmail.com', 'cdcabbb42c07586007f367353c2bd241', 'YP6aWNCsANhgpmQ8vrrmZBb6L54sOxkp', 1, '2012-10-28 00:00:00', '2012-11-16 00:00:00');
INSERT INTO `CustomerLogon` (`CustomerID`, `UserName`, `Pass`, `Salt`, `State`, `DateJoined`, `DateLastModified`) VALUES (4, 'bjorn.hansen@yahoo.no', '9cad8e966c8b47a27e2703e51a75d23e', 'vFDJ8jISdVfCIMkTpbze5ECLMeritDe8', 1, '2012-07-31 00:00:00', '2012-08-14 00:00:00');
INSERT INTO `CustomerLogon` (`CustomerID`, `UserName`, `Pass`, `Salt`, `State`, `DateJoined`, `DateLastModified`) VALUES (5, 'frantisekw@jetbrains.com', '6d465b9782c5a1ffd5e64b8be43a25f1', 't5llWFtASh1LwDjbSuAcA7gZ7d8MBz2J', 1, '2012-08-06 00:00:00', '2012-09-25 00:00:00');
INSERT INTO `CustomerLogon` (`CustomerID`, `UserName`, `Pass`, `Salt`, `State`, `DateJoined`, `DateLastModified`) VALUES (6, 'hholy@gmail.com', '7eb81f3fdd0c1c96951b85905da420f2', 'VoTVT17OHoGxaZwmit3g07uwwdx0FoFE', 1, '2012-11-01 00:00:00', '2012-12-14 00:00:00');
INSERT INTO `CustomerLogon` (`CustomerID`, `UserName`, `Pass`, `Salt`, `State`, `DateJoined`, `DateLastModified`) VALUES (7, 'astrid.gruber@apple.at', '6f8c4eed1a70ab63cc010e49157871fb', 'eWGrN16jTtprvlNS3ynaUUIZwYZSaYv3', 1, '2012-06-05 00:00:00', '2013-01-10 00:00:00');
INSERT INTO `CustomerLogon` (`CustomerID`, `UserName`, `Pass`, `Salt`, `State`, `DateJoined`, `DateLastModified`) VALUES (8, 'fharris@google.com', 'e62798b951bab59d58bcbd6b49159bed', '8kLYNpRXd57yHh2NG8xeMedFLb9q3v4V', 1, '2012-09-25 00:00:00', '2012-11-18 00:00:00');
INSERT INTO `CustomerLogon` (`CustomerID`, `UserName`, `Pass`, `Salt`, `State`, `DateJoined`, `DateLastModified`) VALUES (9, 'jacksmith@microsoft.com', '3ce9cf0d08e544eaace1f5280b7e79ad', 'WLwDFTyhbHpBFySCJ8a6pqgpXkHM1oAV', 1, '2012-11-16 00:00:00', '2013-01-18 00:00:00');
INSERT INTO `CustomerLogon` (`CustomerID`, `UserName`, `Pass`, `Salt`, `State`, `DateJoined`, `DateLastModified`) VALUES (10, 'michelleb@aol.com', 'badc7aadfb35a97f503d2d0643fc48aa', 'LYRv2m2DkHT0er5GqAtnX4DiZ7pAKtA4', 1, '2012-12-07 00:00:00', '2013-03-07 00:00:00');
INSERT INTO `CustomerLogon` (`CustomerID`, `UserName`, `Pass`, `Salt`, `State`, `DateJoined`, `DateLastModified`) VALUES (11, 'tgoyer@apple.com', '9ebc2309a19d8b6cc30a78b627d2a8d0', 'PgJBPfjDqmY30b6w38H0QBqolgyAQPpE', 1, '2013-01-14 00:00:00', '2013-04-19 00:00:00');
INSERT INTO `CustomerLogon` (`CustomerID`, `UserName`, `Pass`, `Salt`, `State`, `DateJoined`, `DateLastModified`) VALUES (12, 'robbrown@shaw.ca', 'acb354fef1df68cea98f75bfb4e11efe', 'NeNAmefofIuB18TsKSlySz8hTLw4NJXv', 1, '2013-02-07 00:00:00', '2013-06-11 00:00:00');
INSERT INTO `CustomerLogon` (`CustomerID`, `UserName`, `Pass`, `Salt`, `State`, `DateJoined`, `DateLastModified`) VALUES (13, 'edfrancis@yachoo.ca', 'd1b76d1c9e9a0af1b243348d6aa208db', 'CdQkKYIAH7784lUQ7CbJtXDwcgCuVnql', 1, '2012-12-20 00:00:00', '2013-01-11 00:00:00');
INSERT INTO `CustomerLogon` (`CustomerID`, `UserName`, `Pass`, `Salt`, `State`, `DateJoined`, `DateLastModified`) VALUES (14, 'mphilips12@shaw.ca', '4d5df99ea28d85bee1943057c0fa5af1', '5JD3H7F7FCgA3XySfVUqn7IvZRRvkyLD', 1, '2012-05-21 00:00:00', '2012-10-28 00:00:00');
INSERT INTO `CustomerLogon` (`CustomerID`, `UserName`, `Pass`, `Salt`, `State`, `DateJoined`, `DateLastModified`) VALUES (15, 'marthasilk@gmail.com', '701a6c379457427da2109b6a5cc4db4e', 'rh5PWxACiKkaWhL8XjRoEiTB4vOjjnRH', 1, '2012-11-17 00:00:00', '2012-12-01 00:00:00');
INSERT INTO `CustomerLogon` (`CustomerID`, `UserName`, `Pass`, `Salt`, `State`, `DateJoined`, `DateLastModified`) VALUES (16, 'aaronmitchell